### ISSUE TITLE
Loading an URL with 3 redirects gives "ERR_ABORTED"

### ISSUE THREAD

**Issue by face-hh** [Lecrapouille/gdcef#68]
```gdscript
browser.load_url("https://duckduckgo.com/?q=test%20%21gi")
```
![image](https://github.com/user-attachments/assets/e59b8e87-46b7-494d-b4af-82cf752e798f)
```gdscript
func _ready():
	browser.connect("on_page_failed_loading", _on_page_failed_loading)

func _on_page_failed_loading(aborted, msg_err, node):
	print_debug(msg_err)
```

![image](https://github.com/user-attachments/assets/25e1086c-38bb-4044-a5a0-b3be82a1843d)

For the record, this issue also happens when a normal webpage redirects multiple times (such as GitHub's login system)

URLs with less than 3 redirects work just fine.
![image](https://github.com/user-attachments/assets/1e88ddc9-9370-47e4-8dc6-c822a98b16c9)

It's not possible to properly debug since the `msg_err` is always `ERR_ABORTED`, which seems to be passed by CEF itself.

```cpp
void GDBrowserView::onLoadError(CefRefPtr<CefBrowser> /*browser*/,
                                CefRefPtr<CefFrame> frame,
                                const bool aborted, const CefString& errorText)
{
    if (frame->IsMain())
    {
        std::string str = errorText.ToString();
        BROWSER_ERROR("has failed loading " << frame->GetURL() << ": " << str);
        godot::String err = str.c_str();
        // Emit signal for Godot script
        emit_signal("on_page_failed_loading", aborted, err, this);
    }
}
```

**Comment by face-hh** [comment]
In case it helps, here are the addon logs:
```js
[2024-08-30 10:32:58] [GDCEF][GDCEF::_bind_methods]
[2024-08-30 10:33:00] [GDCEF][BrowserView::GDBrowserView][-1] Create Godot texture
[2024-08-30 10:33:00] [GDCEF][BrowserView::close][-1]
[2024-08-30 10:33:00] [GDCEF][GDCEF::shutdown]
[2024-08-30 10:33:17] [GDCEF][GDCEF::_bind_methods]
[2024-08-30 10:33:18] [GDCEF][GDCEF::initialize] Launching CEF from Godot editor
[2024-08-30 10:33:18] [GDCEF][GDCEF::initialize] Path where your project Godot files shall be located:"C:\\...\\cef_artifacts"
[2024-08-30 10:33:18] [GDCEF][GDCEF::initialize] [GDCEF][GDCef::_init] CefInitialize
[2024-08-30 10:33:18] [GDCEF][GDCEF::OnBeforeCommandLineProcessing]
[2024-08-30 10:33:18] [GDCEF][GDCEF::OnBeforeCommandLineProcessing] Allow enable-media-stream
[2024-08-30 10:33:18] [GDCEF][GDCEF::initialize] CefInitialize done with success
[2024-08-30 10:33:18] [GDCEF][BrowserView::GDBrowserView][-1] Create Godot texture
[2024-08-30 10:33:18] [GDCEF][BrowserView::resize_][1] 1152 x 578
[2024-08-30 10:33:18] [GDCEF][GDCEF::createBrowser] name: browser_1, url: https://google.com
[2024-08-30 10:33:18] [GDCEF][BrowserView::getTitle][1]
[2024-08-30 10:33:19] [GDCEF][GDCEF::onLoadEnd] has ended loading https://www.google.com/
[2024-08-30 10:33:19] [GDCEF][BrowserView::getURL][1] https://www.google.com/
[2024-08-30 10:33:23] [GDCEF][BrowserView::loadURL][1] https://duckduckgo.com/?q=test%20%21gi
[2024-08-30 10:33:24] [GDCEF][GDCEF::onLoadEnd] has ended loading https://duckduckgo.com/?q=test%20%21gi
[2024-08-30 10:33:24] [GDCEF][BrowserView::getURL][1] https://duckduckgo.com/?q=test%20%21gi
[2024-08-30 10:33:24] [GDCEF][BrowserView::onLoadError][1] has failed loading https://duckduckgo.com/?q=test%20%21gi: ERR_ABORTED
[2024-08-30 10:33:24] [GDCEF][BrowserView::getURL][1] https://duckduckgo.com/?q=test%20%21gi
[2024-08-30 10:33:24] [GDCEF][BrowserView::onLoadError][1] has failed loading https://duckduckgo.com/?q=test%20%21gi: ERR_ABORTED
[2024-08-30 10:33:24] [GDCEF][BrowserView::getURL][1] https://duckduckgo.com/?q=test%20%21gi
[2024-08-30 10:33:24] [GDCEF][BrowserView::onLoadError][1] has failed loading https://duckduckgo.com/?q=test%20%21gi: ERR_ABORTED
[2024-08-30 10:33:24] [GDCEF][BrowserView::getURL][1] https://duckduckgo.com/?q=test%20%21gi
[2024-08-30 10:33:24] [GDCEF][BrowserView::onLoadError][1] has failed loading https://duckduckgo.com/?q=test%20%21gi: ERR_ABORTED
[2024-08-30 10:33:24] [GDCEF][BrowserView::getURL][1] https://duckduckgo.com/?q=test%20%21gi
[2024-08-30 10:33:24] [GDCEF][BrowserView::onLoadError][1] has failed loading https://duckduckgo.com/?q=test%20%21gi: ERR_ABORTED
[2024-08-30 10:33:24] [GDCEF][BrowserView::getURL][1] https://duckduckgo.com/?q=test%20%21gi
// ...
```

**Comment by Lecrapouille** [comment]
Arf! 😱 Complex bug this one. I already had error triggered on basic page but never reached infinite loop. You can disable this trigger, the page could be loaded nicely I hope.

**Comment by face-hh** [comment]
Hey! Thanks for the quick reply.

I've managed to fix the 'infinite loop' by applying some checks on the `_on_page_failed_loading` signal. However, I'm still having trouble with the actual redirecting problem.

> **You can disable this trigger**, the page could be loaded nicely I hope.

Could you please clarify what you meant by that?

**Comment by Lecrapouille** [comment]
@face-hh I'll give a try tonight

**Comment by Lecrapouille** [comment]
@face-hh Ok I reproduce the issue. It loops for ever. As workaround you can comment this line:

https://github.com/Lecrapouille/gdcef/blob/91b365cfd7be508f423420278f257f15892956f2/addons/gdcef/demos/2D/CEF.gd#L99

Can you share your "checks" ?

**Comment by Lecrapouille** [comment]
@face-hh Ok I fixed it. Godot does not like `=` for string

https://github.com/Lecrapouille/gdcef/blob/91b365cfd7be508f423420278f257f15892956f2/addons/gdcef/gdcef/src/gdbrowser.cpp#L307

I tried with latest Godot and CEF. Now on the Demo2D the page shows correctly the error but I do not understand why I have this error anyway. I'll create a fix and a new release

**Comment by face-hh** [comment]
Alright, thank you so much! Love the project

**Comment by Lecrapouille** [comment]
@face-hh the release 0.11.0 is available here https://github.com/Lecrapouille/gdcef/releases/tag/v0.11.0-godot4 (Linux is made and Windows is in progress). Tell me if ok and in this case, I'll submit it to the Godot asset lib.

**Comment by face-hh** [comment]
> @face-hh the release 0.11.0 is available here https://github.com/Lecrapouille/gdcef/releases/tag/v0.11.0-godot4 (Linux is made and Windows is in progress). Tell me if ok and in this case, I'll submit it to the Godot asset lib.

Cool, I'll try it when I'm home and let you know

**Comment by face-hh** [comment]
Hey,

I tried the 0.11.0 version and I'm still experiencing the bug. Here are my logs:
```
ERR_ABORTED
   At: res://Scripts/CEF.gd:85:_on_page_failed_loading()
ERR_ABORTED
   At: res://Scripts/CEF.gd:85:_on_page_failed_loading()
Too many failed loading attempts. Loading Google.com...
Loading blocked. Ignoring request.
```
Code:
```gdscript
var failed_loading_count = 0
var last_failed_loading_time = 0
var is_loading_blocked = false

func _on_page_failed_loading(aborted, msg_err, node):
	var current_time = Time.get_ticks_msec()
	
	if current_time - last_failed_loading_time <= 1000:
		failed_loading_count += 1
	else:
		failed_loading_count = 1
	
	last_failed_loading_time = current_time

	if failed_loading_count >= 3 and !is_loading_blocked:
		is_loading_blocked = true
		print("Too many failed loading attempts. Loading Google.com...")
		node.load_url(HOME_PAGE)
		
		await get_tree().create_timer(2.0).timeout
		is_loading_blocked = false
		failed_loading_count = 0
		return
	
	if is_loading_blocked:
		print("Loading blocked. Ignoring request.")
		return
	
	var html = "<html><body bgcolor=\"white\"><h2>Failed to load URL " + node.get_url()
	print_debug(msg_err)
	if aborted:
		html = html + " aborted by the user!</h2></body></html>"
	else:
		html = html + " with error " + msg_err + "!</h2></body></html>"
	node.load_data_uri(html, "text/html")
```
The URL I tried loading is `https://duckduckgo.com/?q=test%20%21gi`. Unfortunately, the error code is still `ERR_ABORTED`.

I tested both the Release version and the version I compiled on my PC, and the issue occurs in both cases.

**Comment by Lecrapouille** [comment]
For what I see if you remove the callback in the gdscript at the line I gave you or the emit in the C++ code, you will see a single log error. For me the loop is an issue with Godot, not CEF when converting strings from CEF to Godot (or by me) impacting the emit and resulting a loop. I'll try again tonight.

**Comment by Lecrapouille** [comment]
@face-hh As the main CEF dev said in his code: we have to ignore this error. I'm sure why. I've updated the API and demos.
